<?php
require_once('header.php');
require_once('navbar.php');
require_once('searchbar.php');
require_once('login.php');
require_once('content.php');
require_once('ourstory.php');
require_once('footer.php');
?>